name: Latest Medium activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "MEDIUM"
          feed_list: "https://febro.medium.com/feed"
          template: "<tr><td>$title</td><td>$url</td></tr>"
